import { createSlice } from "@reduxjs/toolkit";


const initialState = {
    groups:  [], 
    selectedGroup: null 
};

// Create a group slice
const groupSlice = createSlice({
    name: "group", // Name of the slice
    initialState: initialState, // Initial state
    reducers: {
        // Reducer to set groups data
        setGroups(state, action) {
            state.groups = action.payload; // Update groups array with payload data
        },
        // Reducer to set selected group
        setSelectedGroup(state, action) {
            state.selectedGroup = action.payload; // Update selectedGroup with payload data
        }
    }
});

// Export actions generated by createSlice
export const { setGroups, setSelectedGroup } = groupSlice.actions;

// Export the reducer generated by createSlice
export default groupSlice.reducer;